apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: "{{  .Chart.Name  }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.webapp.port }}
            initialDelaySeconds: 20
            periodSeconds: 60
          volumeMounts:
          - name: config-volume
            mountPath: /StoreWebApp/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-{{ .Values.service.name }}-config
          items:
          - key: checks
            path: checks
          - key: default.json
            path: default.json
