apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-service
  labels:
    app: catalog
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
   - protocol: TCP
     port: {{ .Values.catalog.port }}
     nodePort: {{ .Values.catalog.nodePort }}
