apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-secret
type: Opaque
data:
  mysqlRootPassword: UGFzczRBZG1pbjEyMw==
  mysqlUser: ZGJ1c2Vy
  mysqlPassword: UGFzczRkYlVzM1I=
  mysqlDatabase: aW52ZW50b3J5ZGI=
