apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-secret
type: Opaque
data:
  mysqlRootPassword: <my sql root password>
  mysqlUser: <db user>
  mysqlPassword: <my sql password>
  mysqlDatabase: <db name>
